apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: redis-promise
spec:
  #workerClusterResources:
  xaasRequestPipeline:
  - kirederik/redis-promise
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: redis.promise.example.com
    spec:
      group: promise.example.com
      scope: Namespaced
      names:
        plural: redis
        singular: redis
        kind: redis
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name: {type: string}
                  password: {type: string}
